image:
  repository: wallabag/wallabag
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  path: /read

db:
  host: postgres.databases.svc.cluster.local
  port: "5432"
  name: wallabag
  user: wallabag

redis:
  host: redis-master.databases.svc.cluster.local
  port: "6379"

existingSecret: wallabag-db-secret

persistence:
  size: 5Gi
  nfs:
    server: 192.168.68.100
    path: /mnt/pve/BigData/k3s-shares/wallabag

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
