image:
  repository: linuxserver/transmission
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 9091

ingress:
  path: /torrent

env:
  PUID: "1000"
  PGID: "1000"
  TZ: UTC

persistence:
  config:
    storageClass: nfs-hdd
    size: 1Gi
  downloads:
    size: 500Gi
    nfs:
      server: 192.168.68.100
      path: /mnt/pve/BigData/k3s-shares/transmission

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
