apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: pihole-exporter
spec:
  selector:
    app: pihole-exporter
  ports:
    - name: metrics
      port: 9617
      targetPort: 9617
