apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-downloads
spec:
  capacity:
    storage: {{ .Values.persistence.downloads.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.persistence.downloads.nfs.server }}
    path: {{ .Values.persistence.downloads.nfs.path }}
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-downloads
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size }}
  volumeName: {{ .Release.Name }}-downloads
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
