image:
  repository: ghcr.io/gethomepage/homepage
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: NodePort
  nodePort: 30080
  port: 3000

ingress:
  enabled: true
  path: /home
  className: traefik

config:
  allowedHosts: localhost
  title: Homelab
  kubernetes:
    mode: cluster
  baseUrl: https://192.168.68.150
  services:
    - Media:
        - Jellyfin:
            href: https://192.168.68.150/jellyfin
            icon: jellyfin.png
        - Transmission:
            href: https://192.168.68.150/torrent
            icon: transmission.png
    - Reading:
        - CommaFeed:
            href: https://192.168.68.150/feed
            icon: commafeed.png
            description: RSS reader
        - Linkding:
            href: https://192.168.68.150/links
            icon: linkding.png
            description: Bookmark manager
        - Wallabag:
            href: https://192.168.68.150/read
            icon: wallabag.png
            description: Read-it-later
    - Security:
        - Vaultwarden:
            href: https://192.168.68.150/vault
            icon: vaultwarden.png
        - Pi-hole:
            href: https://pihole.local
            icon: pi-hole.png
            description: DNS ad blocker
    - Monitoring:
        - Grafana:
            href: https://192.168.68.150/grafana
            icon: grafana.png
        - Prometheus:
            href: https://192.168.68.150/prometheus
            icon: prometheus.png
    - Cluster:
        - ArgoCD:
            href: https://192.168.68.150/argo
            icon: argocd.png
        - pgAdmin:
            href: https://192.168.68.150/pgadmin
            icon: pgadmin.png
            description: PostgreSQL admin UI
        - Xtreme Downloader:
            href: https://192.168.68.150/xtreme
            icon: download.png

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 512Mi
