image:
  repository: vaultwarden/server
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  host: vault.local

persistence:
  enabled: true
  size: 1Gi
  nfs:
    server: 192.168.68.100
    path: /mnt/pve/BigData/k3s-shares/vaultwarden

env:
  DOMAIN: https://vault.local
  SIGNUPS_ALLOWED: "true"
  WEBSOCKET_ENABLED: "true"

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 1Gi
